### ISSUE TITLE
Fehler beim Login über ADFS

### ISSUE THREAD

**Issue by Excape** [raphiz/stundenplanplaner#14]
Bei der signin-Methode tritt wohl aufgrund des veränderten ADFS-Login-Screens folgender Fehler auf:

```
Traceback (most recent call last):
  File "demos/export_timetable.py", line 13, in <module>
    response = source.signin(username, password)
  File "/src/planner/datasource.py", line 39, in signin
    self.scraper.signin(user, password)
  File "/src/planner/datasource.py", line 278, in signin
    '__db': html.select('input[name="__db"]')[0]['value'],
IndexError: list index out of range
```

Über VPN funktioniert es übrigens auch nicht. Beim Aufruf über den Browser wird zwar Basic Authentication gemacht, aber zuerst wird weitergeleitet von `unterricht.hsr.ch` auf `adfs.hsr.ch` (302). Das Skript prüft nur, ob ein 401 zurückgegeben wird

```
curl -I https://unterricht.hsr.ch/
HTTP/1.1 302 Found
[...]
```

``` python
def _in_HSR_network(self):
        response = requests.get(self.HSR_BASE_URL)
        return response.status_code == 401
```

**Comment by raphiz** [comment]
Das Problem ist natürlich, da vorher gewisse Werte aus dem HTML geparsed wurden, die dann ans backend gesendet werden (hier  `__db`)
So wies ausschaut braucht es diese Werte nicht mehr.
Ein Post auf `https://adfs.hsr.ch/adfs/ls/?wa=wsignin1.0&wtrealm=https%3a%2f%2funterricht.hsr.ch%2f ` mit den Formdaten:
```
UserName:hsr.ch\<user>
Password: ***
AuthMethod:FormsAuthentication
```
scheint auszureichen.

Das VPN Problem scheint aber toll zu sein, denn evtl. ist so eine einheitliche Lösung - egal ob intern oder extern möglich.

**Comment by raphiz** [comment]
@Excape sollte gefixt sein. Kannst du mir das bestätigen?

**Comment by Excape** [comment]
@raphiz Funktioniert nun. Merci :smiley: :+1:
