### ISSUE TITLE
Bezeichungen bei Seminaren

### ISSUE THREAD

**Issue by Excape** [raphiz/stundenplanplaner#2]
Wenn das Modul "FKIA" gewählt ist, erscheint folgender Fehler:
```
Traceback (most recent call last):
  File "demo.py", line 50, in <module>
    solutions = planner.solve(filters)
  File "/src/planner/planner.py", line 30, in solve
    self._initialize()
  File "/src/planner/planner.py", line 21, in _initialize
    self.lectures = self.backend.lectures_times(self.modules, True)
  File "/src/planner/datasource.py", line 86, in lectures_times
    lectures[module] = self._parse_timetable(self.session.get(timetable_url).text)
  File "/src/planner/datasource.py", line 113, in _parse_timetable
    lesson['abbrev'] = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Dies liegt wohl an der speziellen Bezeichnung (ein Seminar):
![screenshot from 2016-05-24 16-42-19](https://cloud.githubusercontent.com/assets/5650949/15508133/8a72f15c-21ce-11e6-8727-8484593cea96.png)

**Comment by raphiz** [comment]
@Excape weisst du die seX bedeuten?
Der Algorithmus sollte seit 79133ed damit umgehen können - wenn se1, se2 und se3 jeweils unterschiedliche durchführungen sind...

**Comment by raphiz** [comment]
Sollte mit #8 und #9 gelöst sein
