### ISSUE TITLE
Parsen von Seminaren nicht möglich

### ISSUE THREAD

**Issue by jmatj** [raphiz/stundenplanplaner#8]
Bitte in datasource.py Zeile 99 (https://github.com/raphiz/stundenplanplaner/blob/master/planner/datasource.py#L99) ergänzen:

p = re.compile(ur'([A-Za-z0-9]+)-(v|u|p|**se**)([0-9])([0-9]?)')

Dadurch werden Seminare auch geparst. Im Modul FKIA sind diese vorhanden.

Vielen Dank

**Comment by Excape** [comment]
Sollte auch #2 lösen

**Comment by raphiz** [comment]
Habe den Pull-Request gemerged!
